---
- name: Deploy a web application
  hosts: db_and_web_servers
  become: yes
  become_method: sudo
  remote_user: adrian
  tasks:
    - name: Install all required dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openssh-server
        - sudo
        - python3
        - python3-pip
        - python3-venv
    - import_tasks: tasks/deploy_db.yml
    - import_tasks: tasks/deploy_web.yml
      tags: packages