---
- name: Install all required dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openssh-server
    - sudo
    - python3
    - python3-pip
    - python3-venv
  tags: packages
